# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: MrZeFr的小窝
subtitle: 'Hello World'
description: '一个普普通通的小站!'
keywords: 博客
author: MrZeFr
email: mrzefr@mrzefr.cn
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.mrzefr.cn
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category:
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo:
    gitee:
      url: https://SYSTEMWindows11:70ff6f22ec551336abcf868c15078dac@gitee.com/SYSTEMWindows11/mr-ze-fr-blog-server.git
      branch: master
    github:
      url: https://Hi-MrZeFr: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@github.com/Hi-MrZeFr/MrZeFr-Blog.git
      branch: master
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: false
  content_limit: false
  content_limit_delim: " "
  order_by: -date
  icon: icon.jpg
  autodiscovery: true
  template:
# hexo-admin authentification
admin:
  username: MrZeFr
  password_hash: $2a$10$sXzQeO8ZBeWPBvfko7mYZuqBGTGqyTuHq./Z9cHXhCfNVsa.wEtom
  secret: Windowsmzf123456/
nofollow:
  enable: true
  field: site
  exclude:
# abbrlink config
abbrlink:
  alg: crc32      #support crc16(default) and crc32
  rep: hex        #support dec(default) and hex
  drafts: false  #(true)Process draft,(false)Do not process draft. false(default)
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: false  #true(default)
     depth:        #3(default)
     over_write: false
  auto_title: true #enable auto title, it can auto fill the title by path
  auto_date: false #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink. This only updates abbrlink rather than other front variables.
markdown:
  plugins:
    - plugin:
      name: '@neilsustc/markdown-it-katex'
      options:
        strict: false
algolia:
  appId: "UE27RDEC7M"
  apiKey: "b81b18108797e2dc8fa40691d7202d30"
  adminApiKey: "d94142696990ae47c071566e7570aff9"
  chunkSize: 5000
  indexName: "MrZeFr"
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title
plugins:
  - hexo-algoliasearch
hexo_external_link:
  enable: true
  enable_base64_encode: true
  url_param_name: 'url'
  html_file_name: 'go.html'
  target_blank: true
  link_rel: 'external nofollow noopener noreferrer'
  domain: 'blog.mrzefr.cn' # 如果开启了防盗链
  safety_chain: true
  ignore_attrs: 
    - 'data-fancybox'
    - 'ignore-external-link'    
